# No default os and language here, due to special macos config

jobs:
  allow_failures:  # Linux builds currently fail with on Travis, but work on
    - os: linux    # local machine. Allow failures, until reason is found.
  include:
    - name: Python 3.7 on Ubuntu Linux 18.04
      os: linux
      dist: bionic
      language: python
      python: '3.7'
    - name: Python 3.8 on Ubuntu Linux 18.04
      os: linux
      dist: bionic
      language: python
      python: '3.8'
    # See https://blog.travis-ci.com/2019-08-07-extensive-python-testing-on-travis-ci
    # for macos config peculiarities.
    - name: Python 3.7 on MacOS X (xcode 10.2)
      os: osx
      language: shell
      osx_image: xcode10.2
      python: '3.7'
    - name: Python 3.8 on MacOS X (xcode 11.3)
      os: osx
      language: shell
      osx_image: xcode11.3
      python: '3.8'

env:
  global:
  - CACHE_DIR="$HOME/virtualenv"
  - MINICONDA_DIR="$HOME/miniconda"
  - PYTHONIOENCODING=UTF8

before_install:
  - export PATH="${MINICONDA_DIR}/bin:$PATH"
  - bash travis/install-conda.sh
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - conda activate test
  - hash -r
  - bash travis/install-pip.sh

install:
  - python setup.py build
  - python setup.py install

before_script:
  - flake8 --exit-zero .

script:
  - pytest --cov=phenotrex

after_success:
  - codecov

cache:
  - pip
  - ccache
  - packages
  - directories:
      - "$HOME/.cache/pip"
      - "$HOME/virtualenv"
      - "$HOME/miniconda"

branches:
  only:
  - master
  - develop
  - dev

# TODO enable tox usage as originial intended
#
## Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
#install: pip install -U tox-travis
#
## Command to run tests, e.g. python setup.py test
#script: tox
#
## Assuming you have installed the travis-ci CLI tool, after you
## create the Github repo and add it to Travis, run the
## following command to finish PyPI deployment setup:
## $ travis encrypt --add deploy.password
#deploy:
#  provider: pypi
#  distributions: sdist bdist_wheel
#  user: LokiLuciferase
#  password:
#    secure: PLEASE_REPLACE_ME
#  on:
#    tags: true
#    repo: LokiLuciferase/phenotrex
#    python: 3.6
